### ISSUE TITLE
Can't get demo 3 second task to run

### ISSUE THREAD

**Issue by robbiemu** [luoxiu/Schedule#45]
I have this service I would like to run from my root viewcontroller in ios in viewDidLoad.

```swift
    /** every period we process this plan */
    static func periodicallyProcessPlanTask () {
        print("scheduling periodic plan processing")
        
        TaskCenter.default.cancel(byTag: "notificationsDispatch")
        
        print ("still processing")
        let queue = DispatchQueue(label: "notificationsDispatch", qos: .default)

        let newPlan = Plan.after(3.seconds)
        let newTask = newPlan.do(queue: queue) {
            print("periodically processing background notifications")
            PreferencesModel.shared.processBackgroundNotificationsQueue()
        }

        print ("scheduled processing!!")
        TaskCenter.default.addTags(["notificationsDispatch"], to: newTask)
    }
```

note that the print statements are in there to debug. I do call this, which exists in its own PlanService class, from viewdidload:

```swift
class RootViewController: UIViewController {
//...    
    var loadCount = 0

    override func viewDidLoad() {
        super.viewDidLoad()
        
        if loadCount == 0 {
            PlanService.periodicallyProcessPlanTask()
        }
        loadCount += 1
```

and I do see print statements to verify that it did load, but not the one that records it executing:
```
scheduling periodic plan processing
still processing
scheduled processing!!
```

even if I comment out the other line in the task, leaving nothing but a print statement, it does not execute. Also, if I move the task to AppDelegate's didFinishLaunchingWithOptions, it does not run.

If I add "newTask.executeNow()" it _does_ run. but that kinda defeats the purpose (I'd like this to run either every 15 minutes or perhaps every hour). Also, in the debugger I can see that it does have an `estimatedNextExecutionDate` which seems correct.

Where do I have to be to be able to run the function? Do I have to first background the app ni order for it too run or something?

**Comment by luoxiu** [comment]
You need to hold a reference to the task to ensure it won't be released.
