### ISSUE TITLE
Plan.every(5.second).do is not working

### ISSUE THREAD

**Issue by olcayertas** [luoxiu/Schedule#46]
Here is my simple code:
```
task = Plan.every(5.second).do {
    self.checkIfUnauthorized()
}
task?.resume()
```
This is only working one time.
I am running this code on iOS 12.2 with Xcode 10.2.1.

**Comment by LeeCenY** [comment]
@luoxiu  Update 2.0.2 still has such a problem

**Comment by luoxiu** [comment]
Hi, @LeeCenY ! Thanks for the feedback! I can't reproduce this issue here, can you provide me a demo?

**Comment by bynelus** [comment]
I have the same issue. I'm using this pod in my own cocoapod, in that example project. The code works as expected. But when I'm using my own cocoapod (with Schedule underneath) in another project then it only works the first time when I use the `.global()` queue. If I use the `.main` queue, the task is never executed.

**Comment by LeeCenY** [comment]
@luoxiu Sorry, I can't reproduce the Demo now. I am having problems with the CoreBluetooth project. There will be problems in version 2.0.2. It is normal to use version 1.0.0.

**Comment by FunnyFzl** [comment]
I have the same issue.

**Comment by jangsy7883** [comment]
```    
var task: Task?

func setPlan() {
      let plan = Plan.after(3.seconds)
        
      //TEST1 : not working
      let task1 = plan.do {
          print("test 1")
      }
        
      //TEST2 : not working
      let task2 = plan.do {
          print("test 2")
      }
      TaskCenter.default.addTag("test", to: task2)
        
      //TEST3 : working
      task = plan.do {
          print("test 3")
      }
}
```

I have the same issue.
Is TEST1, TEST2 the wrong way?
Do I not know how to use it?

**Comment by ApolloZhu** [comment]
@jangsy7883 no, test1 and test2 won't work. Check the release note: https://github.com/luoxiu/Schedule/releases/tag/2.0.0

To put it in simple terms, tasks [behave like AVAudioPlayer](https://stackoverflow.com/questions/8016765/avaudioplayer-not-playing-any-sound/8415802#8415802) in version 2.x.

**Comment by rickymc** [comment]
Does that mean that TaskCenter has weak references to Tasks ?

**Comment by ApolloZhu** [comment]
Yes, @rickymc

https://github.com/luoxiu/Schedule/blob/4bb334fda460ea558437a6d84b3d32c84a433e28/Sources/Schedule/TaskCenter.swift#L7
