### ISSUE TITLE
v1.0.0 控制器返回上一层，调用 deinit 了，但是计时器还在回调

### ISSUE THREAD

**Issue by AbeiOS** [luoxiu/Schedule#48]
![image](https://user-images.githubusercontent.com/12441461/59735661-14e15f80-9289-11e9-91f4-6de76327cdd8.png)
![image](https://user-images.githubusercontent.com/12441461/59735696-48bc8500-9289-11e9-81db-5abcff5fa464.png)

**Comment by luoxiu** [comment]
试一下 v2 啦

**Comment by AbeiOS** [comment]
v2 不支持 iOS 9 是吗，我这边 pod 导入无法安装

**Comment by luoxiu** [comment]
@AbeiOS humm... 因为用了 `Timer` 的新 API，所以把版本限制到了 iOS 10，我试着找下 workaround，感谢反馈！

**Comment by luoxiu** [comment]
@AbeiOS 嗨，我用了一个替代方法，Schedule 现在应该可以跑在 iOS 9 上了，试试吧！欢迎继续反馈或者直接提交 pr！

**Comment by AbeiOS** [comment]
好的感谢

**Comment by AbeiOS** [comment]
作者你好，v2.0.3 还是存在不销毁的问题
创建：
   · var weakTask: Task?
            
   ·  weakTask = Plan.every(1.second).do(mode: .common) {
          print("计时器调用")
      }

    deinit {
        print("控制器被销毁了")
        TaskCenter.default.removeAll()
    }
![image](https://user-images.githubusercontent.com/12441461/59740073-8fb27680-9299-11e9-878f-307ec7970f80.png)

**Comment by AbeiOS** [comment]
是不是我的用法不对

**Comment by AbeiOS** [comment]
好了，看了 TaskCenter 的实现
