### ISSUE TITLE
代码不执行

### ISSUE THREAD

**Issue by Ssunnyday** [luoxiu/Schedule#49]
直接使用示例代码，在pod文件中断点直接跳出。
版本：2.0.2
<img width="1276" alt="屏幕快照 2019-07-10 下午6 52 58" src="https://user-images.githubusercontent.com/34640690/60964040-e9600b00-a344-11e9-9721-b93edfe5f2f6.png">

同事用手动拖入的方法也不执行

截图我是一个demo，也不执行

**Comment by luoxiu** [comment]
要持有这个 task 哦，不然对象会被销毁。

**Comment by Ssunnyday** [comment]
![WechatIMG20](https://user-images.githubusercontent.com/34640690/61015927-5e245b00-a3c0-11e9-9dd3-da50e08433a6.jpeg)
那请问这又是啥情况？ - -

**Comment by Ssunnyday** [comment]
> 要持有这个 task 哦，不然对象会被销毁。

![WechatIMG20](https://user-images.githubusercontent.com/34640690/61015955-74321b80-a3c0-11e9-81fe-32ad9aebfce4.jpeg)
这又是什么情况....  - -

**Comment by luoxiu** [comment]
@Ssunnyday 你在用 2.x 吗？我这边没问题啊……
![屏幕快照 2019-07-11 上午10 11 25](https://user-images.githubusercontent.com/18638838/61017029-5bc40000-a3c4-11e9-9007-f353b3e7ba65.png)

**Comment by Ssunnyday** [comment]
> @Ssunnyday 你在用 2.x 吗？我这边没问题啊……
> ![屏幕快照 2019-07-11 上午10 11 25](https://user-images.githubusercontent.com/18638838/61017029-5bc40000-a3c4-11e9-9007-f353b3e7ba65.png)

搞清楚了，我使用的是最新版2.0.3 这种情况下必须使用全局变量，同事使用的1.7，可以使用局部。
感谢

**Comment by L1cardo** [comment]
> > @Ssunnyday 你在用 2.x 吗？我这边没问题啊……
> > ![屏幕快照 2019-07-11 上午10 11 25](https://user-images.githubusercontent.com/18638838/61017029-5bc40000-a3c4-11e9-9007-f353b3e7ba65.png)
> 
> 搞清楚了，我使用的是最新版2.0.3 这种情况下必须使用全局变量，同事使用的1.7，可以使用局部。
> 感谢

你好，能麻烦讲一下你是怎么解决的吗？

**Comment by luoxiu** [comment]
@L1cardo 

为了解决很容易被忽视的内存泄漏问题，在 2.0  里，你需要显式地持有 task：

```swift
class YourClass {
    var task: Task?
    func setupJob() {
        self.task = Plan.after(1.second).do { }
    }
}
```

可以搜索一下作用域，然后了解一下[引用计数](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/24_automatic_reference_counting)。

**Comment by L1cardo** [comment]
> @L1cardo
> 
> 为了解决很容易被忽视的内存泄漏问题，在 2.0 里，你需要显式地持有(retain) task：
> 
> ```swift
> class YourClass {
>     var task: Task?
>     func setupJob() {
>         self.task = Plan.after(1.second).do { }
>     }
> }
> ```
> 
> 可以搜索一下作用域，然后了解一下[引用计数](https://swiftgg.gitbook.io/swift/swift-jiao-cheng/24_automatic_reference_counting)。

嗯嗯 才发现你上面的 task 是 Task 类型，你在文档里也没说，我以为 task 也是 Plan。
现在我的问题已经解决了，谢谢了

**Comment by luoxiu** [comment]
@L1cardo 没事啦，学习 swift 有什么问题也可以再问我！😉
