### ISSUE TITLE
'TaskCenter' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by maxgribov** [luoxiu/Schedule#52]
when I try to initialize TaskCenter:
```swift
let taskCeneter = TaskCenter()
```
 I get this error:
`'TaskCenter' initializer is inaccessible due to 'internal' protection level`

As long as you do not implement init() explicitly, it is marked as internal by default. You need to overwrite that permission level to be able to instantiate from outside your framework.

Or is there some special reason why you don't want to make it available ?

**Comment by luoxiu** [comment]
Wow, sorry, my bad! 
I will fix it.
