### ISSUE TITLE
struct `Plan` api errors

### ISSUE THREAD

**Issue by maxgribov** [luoxiu/Schedule#53]
```swift
let t3 = Plan.every(.firday).at("9:00 pm").do { }
```
error: `Reference to member 'firday' cannot be resolved without a contextual type`

```swift
let t4 = Plan.every("tuesday").at("9:00 pm").do { }
```
error: `Static member 'at' cannot be used on instance of type 'Plan'`

the first option from the documentation...
using: Xcode 11.1, swift 5

**Comment by maxgribov** [comment]
<img width="1271" alt="Screenshot 2019-10-16 at 18 43 46" src="https://user-images.githubusercontent.com/6514571/66935612-f3309300-f044-11e9-9998-61bc4d7361d1.png">

**Comment by maxgribov** [comment]
in the first option just a typo in the word `friday`

**Comment by luoxiu** [comment]
Hi @maxgribov ,

`firday` is a typo in the demo on README, 😅, you should use `friday` in code.

`at` is an instance method of `DateMiddleware`, `Plan` also has a static method named `at`. You can use them as blow:

```swift
let dates = Plan.every(.monday)  // DateMiddleware
let plan = dates.at("9:00")  // Plan

// or
let date = Date() + 1.hour  // Date
let plan = Plan.at(date) // Plan
```

**Comment by maxgribov** [comment]
thank you, but my goal is to translate such strings into timers: “every tuesday at 9am”, “everday at noon”, “every 30 minutes”, “oct 1st at 1pm”, “monday at 2pm”, etc.

**Comment by luoxiu** [comment]
Sorry, parsing such strings is not yet supported. 
Maybe you can make a pr! This feature should be simple to implement with RegExp.
