### ISSUE TITLE
Mac没有响应

### ISSUE THREAD

**Issue by L1cardo** [luoxiu/Schedule#56]
我作为按键事件来执行，没有任何响应
xcode 11.2
![image](https://user-images.githubusercontent.com/33802186/68081952-2353a080-fe51-11e9-86a2-3ecf5c870765.png)

**Comment by luoxiu** [comment]
你应该持有这个 task，不然它会 deinit。

**Comment by L1cardo** [comment]
> 你应该持有这个 task，不然它会 deinit。

我是初学者，持有是什么意思....  能稍微详细一点吗，谢谢啦

**Comment by luoxiu** [comment]
就是引用啦，不然会释放。作用域，引用计数。每个人都是从初学者过来的！😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by L1cardo** [comment]
好的谢谢   麻烦你了
