### ISSUE TITLE
Can't running

### ISSUE THREAD

**Issue by a7e6j2** [luoxiu/Schedule#61]
```

import SwiftUI
import Schedule

struct TestView: View {
	
		var body: some View {
		HStack {
			
			
			Button(action:{
				
			
				let plan = Plan.after(3.seconds)
				let task = plan.do {
					print("test 3")
				}
				print("created task")
				//task.executeNow()
			}){
				
				Text("test")
			}

	}
}



```

Hello, I am developing an app with SWIFTUI, but I don't know how to invoke the schedule. it output nothing for me. needs any setup for it?

**Comment by luoxiu** [comment]
You need to hold the `plan` you created outside the scope, or it will cancel the scheduled task when deinitialize.

ref: https://docs.swift.org/swift-book/LanguageGuide/Deinitialization.html

**Comment by a7e6j2** [comment]
could you give me some example. I have tried to move the "var plan? = Plan" to the outside. but it still can not work.

**Comment by a7e6j2** [comment]
`
import SwiftUI
import Schedule

struct PrefView: View {
	@Binding var showPrefs: Bool
	@State private var cate = 0
	@State private var nowTime = 0
	@State var bTimer: Timer?
	
	
	var body: some View {
		var plan : Plan?
		
		return NavigationView {
			
			Form{
				
				Section(header: Text("Alert Setting")) {
					
					Picker(selection: $cate,  label:Text("Alert Sound")){
						ForEach( 0 ..< ALERT_SOUND.count) { index in
							
							Text(ALERT_SOUND[index][0]).tag(index)
						}
						
					}
				}
				Button(action:{
					
					plan = Plan.after(3.seconds)
					let task = plan?.do {
						print("ok")
						self.nowTime = self.nowTime + 1
					}
					print(task?.estimatedNextExecutionDate!)
					/*
					var timeLeft = 3600
					self.bTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { timer in
						
						timeLeft -= 1
						self.nowTime = timeLeft
						if(timeLeft == 0){
							self.bTimer?.invalidate()
						}
					}
					RunLoop.current.add(self.bTimer!, forMode: RunLoop.Mode.common)
					*/
				}){
					
					Text("test \(self.nowTime)")
				}
				
				
			}
			
				
				
				
			.navigationBarTitle(Text("Settings"), displayMode: .inline)
			.navigationBarItems(trailing: Button(action: {
				self.showPrefs = false
			}) {
				Text("Done").bold()
			})
		}
	}
}


`

**Comment by a7e6j2** [comment]
could you please provide an example in SwiftUI scenario？ thanks！

**Comment by luoxiu** [comment]
Sorry, my typo... You should hold the `task` object, 🤦‍♂️

**Comment by ApolloZhu** [comment]
And I suppose it has to be stored outside of `var body`

**Comment by a7e6j2** [comment]
OK,thank you.
